"""UI-only layout and rendering parameters."""
from __future__ import annotations

STICKER_ALPHA_THRESHOLD = 8
STICKER_FRAME_INTERVAL_MS = 120

BUBBLE_MIN_HEIGHT = 88
BUBBLE_TOP = 7
BUBBLE_TAIL_HEIGHT = 16
BUBBLE_BOTTOM_PAD = 9
BUBBLE_MIN_WIDTH = 202
BUBBLE_MAX_WIDTH = 420
BUBBLE_BODY_MIN_HEIGHT = 56
BUBBLE_BODY_MAX_HEIGHT = 320
BUBBLE_TEXT_PAD_X = 12
BUBBLE_TEXT_PAD_Y = 10
MAX_BUBBLE_TEXT_CHARS = 520

CHAT_BUTTON_MIN_SIZE = 30
CHAT_BUTTON_MAX_SIZE = 44
ACTION_BUTTON_MIN_SIZE = 32
ACTION_BUTTON_MAX_SIZE = 42
ACTION_BUTTON_GAP = 8
ACTION_BUTTON_STICKER_GAP = 9
ACTION_BUTTON_OUTER_PAD = 8

DROP_HOTZONE_PAD = 30
DROP_EFFECT_DURATION = 0.9
DRAG_RELEASE_EFFECT_DURATION = 0.22
CHAT_BUTTON_MARGIN = 4
WINDOW_PAD = 15

TODO_BUBBLE_MAX_VISIBLE = 6
TODO_BUBBLE_GAP = 8
TODO_BUBBLE_TOP = 7
TODO_BUBBLE_MIN_WIDTH = 220
TODO_BUBBLE_MAX_WIDTH = 390
TODO_BUBBLE_TEXT_PAD_X = 12
TODO_BUBBLE_TEXT_PAD_Y = 9
TODO_BUBBLE_MIN_HEIGHT = 50
TODO_BUBBLE_MAX_HEIGHT = 96

FULLSCREEN_ALERT_DURATION_MS = 4_200
