"""Conversation-memory defaults."""
from __future__ import annotations

DEFAULT_MEMORY_ENABLED = False
DEFAULT_MEMORY_TURNS = 8
MAX_MEMORY_TURNS = 24
DEFAULT_LONG_TERM_MEMORY_ENABLED = False
DEFAULT_LONG_TERM_MEMORY_ITEMS = 12
MAX_LONG_TERM_MEMORY_ITEMS = 40
