"""Sticker animation constants."""
from __future__ import annotations

STICKER_ACTION_IDLE = "idle"
STICKER_ACTION_TAP = "tap"
STICKER_ACTION_DRAG = "drag"
STICKER_ACTION_THINKING = "thinking"
STICKER_ACTION_SPEAKING = "speaking"
STICKER_ACTION_ALERT = "alert"
STICKER_ACTION_DROP_FILE = "drop_file"
STICKER_ACTION_ERROR = "error"
STICKER_ACTIONS = (
    STICKER_ACTION_IDLE,
    STICKER_ACTION_TAP,
    STICKER_ACTION_DRAG,
    STICKER_ACTION_THINKING,
    STICKER_ACTION_SPEAKING,
    STICKER_ACTION_ALERT,
    STICKER_ACTION_DROP_FILE,
    STICKER_ACTION_ERROR,
)
STICKER_ACTION_LABELS = {
    STICKER_ACTION_IDLE: "待机 idle",
    STICKER_ACTION_TAP: "点击 tap",
    STICKER_ACTION_DRAG: "拖动 drag",
    STICKER_ACTION_THINKING: "思考 thinking",
    STICKER_ACTION_SPEAKING: "说话 speaking",
    STICKER_ACTION_ALERT: "提醒 alert",
    STICKER_ACTION_DROP_FILE: "拖入文件 drop_file",
    STICKER_ACTION_ERROR: "错误 error",
}
MAX_STICKER_FRAMES = 64
STICKER_ALPHA_THRESHOLD = 8
STICKER_FRAME_INTERVAL_MS = 120
STICKER_IMAGE_FILTER = "Images (*.png *.jpg *.jpeg *.webp *.bmp);;All Files (*)"
STICKER_IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".webp", ".bmp")
DEFAULT_STICKER_ANIMATION_SPEED = 1.0
MIN_STICKER_ANIMATION_SPEED = 0.25
MAX_STICKER_ANIMATION_SPEED = 4.0
